services:
  education-content-service:
    container_name: education-content-service
    build:
      context: ./backend/EducationContentService
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:9001
    env_file:
      - education.service.env
    restart: always
  seq:
    container_name: seq
    image: datalust/seq:latest    
    ports:
      - "5342:5341" # HTTP API and UI
      - "8081:80"   # Optional: if you want to expose Seq on port 80 directly
    environment:
      ACCEPT_EULA: 'Y' # Required to accept the Seq End User License Agreement
      SEQ_FIRSTRUN_NOAUTHENTICATION: 'true'
    restart: always
  postgres:  
    container_name: postgres-education-service
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: education-service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5